
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author william.li
 */
public class MainScreen extends javax.swing.JFrame {

    private final FlashcardManager flashcardManager;
    private final DefaultListModel<String> cardListModel;

    // True if the back of the card is shown
    private boolean isFlipped = false;
    private int currentIndex = 0;

    /**
     * Creates new form Cardbulider
     */
    public MainScreen() {
        initComponents();
        setTitle("Flashcard Builder");
        setLocationRelativeTo(null);
        this.setVisible(true);

        flashcardManager = new FlashcardManager();
        flashcardManager.loadFromFile();

        cardListModel = new DefaultListModel<>();
        cardList.setModel(cardListModel);
        
        refreshCardList();
    }

    private void refreshCardList() {
        cardListModel.clear();

        ArrayList<Flashcard> flashcards = flashcardManager.getCards();
        for (Flashcard card : flashcards) {
            cardListModel.addElement(card.getFront());
        }
    }

    private boolean doesFlashcardExist(String front) {
        ArrayList<Flashcard> cards = flashcardManager.getCards();

        for (Flashcard card : cards) {
            String cardFront = card.getFront();
            if (cardFront.equalsIgnoreCase(front)) {
                return true;
            }
        }
        return false;
    }

    private void updateStudyCard() {
        ArrayList<Flashcard> cards = flashcardManager.getCards();
        Flashcard card = cards.get(currentIndex);

        if (isFlipped) {
            cardTextPane.setText(card.getBack());
        } else {
            cardTextPane.setText(card.getFront());
        }

        cardProgressLabel.setText("Card " + (currentIndex + 1) + " of " + cards.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainFrame = new javax.swing.JPanel();
        menuCard = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        spacerLabel = new javax.swing.JLabel();
        menuButtons = new javax.swing.JPanel();
        buildButton = new javax.swing.JButton();
        studyButton = new javax.swing.JButton();
        viewAllButton = new javax.swing.JButton();
        buildCard = new javax.swing.JPanel();
        buildCardLabel = new javax.swing.JLabel();
        frontBackPanel = new javax.swing.JPanel();
        frontLabel = new javax.swing.JLabel();
        frontTextField = new javax.swing.JTextField();
        backLabel = new javax.swing.JLabel();
        backTextField = new javax.swing.JTextField();
        addPanel = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        addCard = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        validationLabel = new javax.swing.JLabel();
        backPanel = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        buildBackButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        studyCard = new javax.swing.JPanel();
        cardProgressLabel = new javax.swing.JLabel();
        cardScrollPane = new javax.swing.JScrollPane();
        cardTextPane = new javax.swing.JTextPane();
        buttonGroup = new javax.swing.JPanel();
        prevButton = new javax.swing.JButton();
        flipButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        studyBackButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        viewAllCard = new javax.swing.JPanel();
        allCardsLabel = new javax.swing.JLabel();
        listScrollPane = new javax.swing.JScrollPane();
        cardList = new javax.swing.JList<>();
        viewAllButtonGroup = new javax.swing.JPanel();
        removeButton = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        viewAllBackButton = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainFrame.setPreferredSize(new java.awt.Dimension(262, 263));
        mainFrame.setLayout(new java.awt.CardLayout());

        menuCard.setLayout(new java.awt.GridLayout(4, 0));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Flashcard Builder");
        menuCard.add(titleLabel);
        menuCard.add(spacerLabel);

        menuButtons.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        buildButton.setText("Build");
        buildButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buildButtonMouseClicked(evt);
            }
        });
        menuButtons.add(buildButton);

        studyButton.setText("Study");
        studyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studyButtonMouseClicked(evt);
            }
        });
        menuButtons.add(studyButton);

        viewAllButton.setText("View All");
        viewAllButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllButtonMouseClicked(evt);
            }
        });
        menuButtons.add(viewAllButton);

        menuCard.add(menuButtons);

        mainFrame.add(menuCard, "menuCard");

        buildCard.setPreferredSize(new java.awt.Dimension(400, 300));
        buildCard.setLayout(new java.awt.GridLayout(4, 0, 0, 20));

        buildCardLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        buildCardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildCardLabel.setText("Build Card");
        buildCard.add(buildCardLabel);

        frontBackPanel.setLayout(new java.awt.GridLayout(2, 4, 0, 10));

        frontLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        frontLabel.setText("Front");
        frontBackPanel.add(frontLabel);

        frontTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        frontBackPanel.add(frontTextField);

        backLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backLabel.setText("Back");
        frontBackPanel.add(backLabel);

        backTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        frontBackPanel.add(backTextField);

        buildCard.add(frontBackPanel);

        addPanel.setLayout(new java.awt.GridLayout(2, 2));
        addPanel.add(filler3);

        addCard.setText("Add card");
        addCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCardMouseClicked(evt);
            }
        });
        addPanel.add(addCard);
        addPanel.add(filler4);
        addPanel.add(validationLabel);

        buildCard.add(addPanel);

        backPanel.setLayout(new java.awt.GridLayout(2, 3, 80, 0));
        backPanel.add(filler5);
        backPanel.add(filler6);
        backPanel.add(filler7);

        buildBackButton.setText("Back");
        buildBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buildBackButtonMouseClicked(evt);
            }
        });
        backPanel.add(buildBackButton);
        backPanel.add(filler2);

        buildCard.add(backPanel);

        mainFrame.add(buildCard, "buildCard");

        studyCard.setLayout(new java.awt.BorderLayout(0, 10));

        cardProgressLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cardProgressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardProgressLabel.setText("Card");
        studyCard.add(cardProgressLabel, java.awt.BorderLayout.PAGE_START);

        cardScrollPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cardScrollPane.setPreferredSize(new java.awt.Dimension(500, 200));

        cardTextPane.setEditable(false);
        cardTextPane.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cardTextPane.setFocusable(false);
        cardTextPane.setOpaque(false);
        cardScrollPane.setViewportView(cardTextPane);

        studyCard.add(cardScrollPane, java.awt.BorderLayout.CENTER);

        buttonGroup.setLayout(new java.awt.GridLayout(2, 3, 80, 20));

        prevButton.setText("Prev");
        prevButton.setPreferredSize(new java.awt.Dimension(80, 36));
        prevButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevButtonMouseClicked(evt);
            }
        });
        buttonGroup.add(prevButton);

        flipButton.setText("Flip");
        flipButton.setPreferredSize(new java.awt.Dimension(80, 36));
        flipButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flipButtonMouseClicked(evt);
            }
        });
        buttonGroup.add(flipButton);

        nextButton.setText("Next");
        nextButton.setPreferredSize(new java.awt.Dimension(80, 36));
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonMouseClicked(evt);
            }
        });
        buttonGroup.add(nextButton);

        studyBackButton.setText("Back");
        studyBackButton.setPreferredSize(new java.awt.Dimension(100, 40));
        studyBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studyBackButtonMouseClicked(evt);
            }
        });
        buttonGroup.add(studyBackButton);
        buttonGroup.add(filler1);

        studyCard.add(buttonGroup, java.awt.BorderLayout.SOUTH);

        mainFrame.add(studyCard, "studyCard");

        viewAllCard.setLayout(new java.awt.BorderLayout(0, 10));

        allCardsLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        allCardsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allCardsLabel.setText("All Cards");
        viewAllCard.add(allCardsLabel, java.awt.BorderLayout.NORTH);

        listScrollPane.setViewportView(cardList);

        viewAllCard.add(listScrollPane, java.awt.BorderLayout.CENTER);

        viewAllButtonGroup.setLayout(new java.awt.GridLayout(2, 3, 80, 20));

        removeButton.setText("Remove");
        removeButton.setPreferredSize(new java.awt.Dimension(80, 36));
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeButtonMouseClicked(evt);
            }
        });
        viewAllButtonGroup.add(removeButton);
        viewAllButtonGroup.add(filler9);
        viewAllButtonGroup.add(filler10);

        viewAllBackButton.setText("Back");
        viewAllBackButton.setPreferredSize(new java.awt.Dimension(80, 36));
        viewAllBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllBackButtonMouseClicked(evt);
            }
        });
        viewAllButtonGroup.add(viewAllBackButton);
        viewAllButtonGroup.add(filler8);

        viewAllCard.add(viewAllButtonGroup, java.awt.BorderLayout.SOUTH);

        mainFrame.add(viewAllCard, "viewAllCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studyButtonMouseClicked
        CardLayout layout = (CardLayout) mainFrame.getLayout();
        layout.show(mainFrame, "studyCard");
        isFlipped = false;
        updateStudyCard();
    }//GEN-LAST:event_studyButtonMouseClicked

    private void buildButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildButtonMouseClicked
        CardLayout layout = (CardLayout) mainFrame.getLayout();
        layout.show(mainFrame, "buildCard");
    }//GEN-LAST:event_buildButtonMouseClicked

    private void viewAllButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllButtonMouseClicked
        CardLayout layout = (CardLayout) mainFrame.getLayout();
        layout.show(mainFrame, "viewAllCard");
    }//GEN-LAST:event_viewAllButtonMouseClicked

    private void buildBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildBackButtonMouseClicked
        CardLayout layout = (CardLayout) mainFrame.getLayout();
        layout.show(mainFrame, "menuCard");
        frontTextField.setText("");
        backTextField.setText("");
        validationLabel.setText("");
    }//GEN-LAST:event_buildBackButtonMouseClicked

    private void addCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCardMouseClicked
        String frontText = frontTextField.getText();
        String backText = backTextField.getText();

        if (frontText.isBlank() || backText.isBlank()) {
            validationLabel.setText("Please fill in all fields");
            validationLabel.setForeground(Color.red);
            return;
        }

        // Check for duplicate
        if (doesFlashcardExist(frontText)) {
            validationLabel.setText("Flash card already added");
            validationLabel.setForeground(Color.red);
            return;
        }

        Flashcard newCard = new Flashcard(frontText, backText);
        flashcardManager.addCard(newCard);
        refreshCardList();

        validationLabel.setText("Card added!");
        validationLabel.setForeground(Color.green);
        frontTextField.setText("");
        backTextField.setText("");
    }//GEN-LAST:event_addCardMouseClicked

    private void studyBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studyBackButtonMouseClicked
        CardLayout layout = (CardLayout) mainFrame.getLayout();
        layout.show(mainFrame, "menuCard");
    }//GEN-LAST:event_studyBackButtonMouseClicked

    private void viewAllBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllBackButtonMouseClicked
        CardLayout layout = (CardLayout) mainFrame.getLayout();
        layout.show(mainFrame, "menuCard");
    }//GEN-LAST:event_viewAllBackButtonMouseClicked

    private void removeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeButtonMouseClicked
        int index = cardList.getSelectedIndex();
        flashcardManager.removeCard(index);

        refreshCardList();
    }//GEN-LAST:event_removeButtonMouseClicked

    private void flipButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flipButtonMouseClicked
        isFlipped = !isFlipped;
        updateStudyCard();
    }//GEN-LAST:event_flipButtonMouseClicked

    private void prevButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevButtonMouseClicked
        isFlipped = false;
        currentIndex--;
        
        if (currentIndex < 0) {
            currentIndex = flashcardManager.getCardCount() - 1;
        }
        
        updateStudyCard();
    }//GEN-LAST:event_prevButtonMouseClicked

    private void nextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseClicked
        isFlipped = false;
        currentIndex++;
        
        if(currentIndex >= flashcardManager.getCardCount()){
            currentIndex = 0;
        }
        
        updateStudyCard();
    }//GEN-LAST:event_nextButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCard;
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel allCardsLabel;
    private javax.swing.JLabel backLabel;
    private javax.swing.JPanel backPanel;
    private javax.swing.JTextField backTextField;
    private javax.swing.JButton buildBackButton;
    private javax.swing.JButton buildButton;
    private javax.swing.JPanel buildCard;
    private javax.swing.JLabel buildCardLabel;
    private javax.swing.JPanel buttonGroup;
    private javax.swing.JList<String> cardList;
    private javax.swing.JLabel cardProgressLabel;
    private javax.swing.JScrollPane cardScrollPane;
    private javax.swing.JTextPane cardTextPane;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton flipButton;
    private javax.swing.JPanel frontBackPanel;
    private javax.swing.JLabel frontLabel;
    private javax.swing.JTextField frontTextField;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JPanel menuButtons;
    private javax.swing.JPanel menuCard;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel spacerLabel;
    private javax.swing.JButton studyBackButton;
    private javax.swing.JButton studyButton;
    private javax.swing.JPanel studyCard;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel validationLabel;
    private javax.swing.JButton viewAllBackButton;
    private javax.swing.JButton viewAllButton;
    private javax.swing.JPanel viewAllButtonGroup;
    private javax.swing.JPanel viewAllCard;
    // End of variables declaration//GEN-END:variables
}
