
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author william.li
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form Cardbulider
     */
    public MainScreen() {
        initComponents();

        setTitle("Flashcard Builder");
        setLocationRelativeTo(null);

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainFrame = new javax.swing.JPanel();
        menuCard = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        spacerLabel = new javax.swing.JLabel();
        menuButtons = new javax.swing.JPanel();
        buildButton = new javax.swing.JButton();
        studyButton = new javax.swing.JButton();
        viewAllButton = new javax.swing.JButton();
        buildCard = new javax.swing.JPanel();
        buildCardLabel = new javax.swing.JLabel();
        frontBackPanel = new javax.swing.JPanel();
        frontLabel = new javax.swing.JLabel();
        frontTextField = new javax.swing.JTextField();
        backLabel = new javax.swing.JLabel();
        backTextField = new javax.swing.JTextField();
        addPanel = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        addCard = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        errorLabel = new javax.swing.JLabel();
        backPanel = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        backButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        studyCard = new javax.swing.JPanel();
        flashcardPanel = new javax.swing.JPanel();
        studyLabel = new javax.swing.JLabel();
        buttonGroup = new javax.swing.JPanel();
        prevButton = new javax.swing.JButton();
        flipButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        studyBackButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        viewAllCard = new javax.swing.JPanel();
        allCardsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        viewAllButtonGroup = new javax.swing.JPanel();
        removeButton = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        viewAllBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainFrame.setPreferredSize(new java.awt.Dimension(262, 263));
        mainFrame.setLayout(new java.awt.CardLayout());

        menuCard.setLayout(new java.awt.GridLayout(4, 0));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Flashcard Builder");
        menuCard.add(titleLabel);
        menuCard.add(spacerLabel);

        menuButtons.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        buildButton.setText("Build");
        buildButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buildButtonMouseClicked(evt);
            }
        });
        menuButtons.add(buildButton);

        studyButton.setText("Study");
        studyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studyButtonMouseClicked(evt);
            }
        });
        menuButtons.add(studyButton);

        viewAllButton.setText("View All");
        viewAllButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllButtonMouseClicked(evt);
            }
        });
        menuButtons.add(viewAllButton);

        menuCard.add(menuButtons);

        mainFrame.add(menuCard, "menuCard");

        buildCard.setPreferredSize(new java.awt.Dimension(400, 300));
        buildCard.setLayout(new java.awt.GridLayout(4, 0, 0, 20));

        buildCardLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        buildCardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildCardLabel.setText("Build Card");
        buildCard.add(buildCardLabel);

        frontBackPanel.setLayout(new java.awt.GridLayout(2, 4, 0, 10));

        frontLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        frontLabel.setText("Front");
        frontBackPanel.add(frontLabel);

        frontTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        frontBackPanel.add(frontTextField);

        backLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backLabel.setText("Back");
        frontBackPanel.add(backLabel);

        backTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        frontBackPanel.add(backTextField);

        buildCard.add(frontBackPanel);

        addPanel.setLayout(new java.awt.GridLayout(2, 2));
        addPanel.add(filler3);

        addCard.setText("Add card");
        addPanel.add(addCard);
        addPanel.add(filler4);
        addPanel.add(errorLabel);

        buildCard.add(addPanel);

        backPanel.setLayout(new java.awt.GridLayout(2, 3));
        backPanel.add(filler5);
        backPanel.add(filler6);
        backPanel.add(filler7);

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        backPanel.add(backButton);
        backPanel.add(filler2);

        buildCard.add(backPanel);

        mainFrame.add(buildCard, "buildCard");

        studyCard.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout flashcardPanelLayout = new javax.swing.GroupLayout(flashcardPanel);
        flashcardPanel.setLayout(flashcardPanelLayout);
        flashcardPanelLayout.setHorizontalGroup(
            flashcardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        flashcardPanelLayout.setVerticalGroup(
            flashcardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        studyCard.add(flashcardPanel, java.awt.BorderLayout.CENTER);

        studyLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        studyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studyLabel.setText("Study");
        studyCard.add(studyLabel, java.awt.BorderLayout.PAGE_START);

        buttonGroup.setLayout(new java.awt.GridLayout(2, 3, 80, 20));

        prevButton.setText("Prev");
        prevButton.setPreferredSize(new java.awt.Dimension(80, 36));
        buttonGroup.add(prevButton);

        flipButton.setText("Flip");
        flipButton.setPreferredSize(new java.awt.Dimension(80, 36));
        buttonGroup.add(flipButton);

        nextButton.setText("Next");
        nextButton.setPreferredSize(new java.awt.Dimension(80, 36));
        buttonGroup.add(nextButton);

        studyBackButton.setText("Back");
        studyBackButton.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonGroup.add(studyBackButton);
        buttonGroup.add(filler1);

        studyCard.add(buttonGroup, java.awt.BorderLayout.SOUTH);

        mainFrame.add(studyCard, "studyCard");

        viewAllCard.setLayout(new java.awt.BorderLayout());

        allCardsLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        allCardsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allCardsLabel.setText("All Cards");
        viewAllCard.add(allCardsLabel, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(jList1);

        viewAllCard.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        viewAllButtonGroup.setLayout(new java.awt.GridLayout(2, 3, 80, 20));

        removeButton.setText("Remove");
        removeButton.setPreferredSize(new java.awt.Dimension(80, 36));
        viewAllButtonGroup.add(removeButton);
        viewAllButtonGroup.add(filler8);

        viewAllBackButton.setText("Back");
        viewAllBackButton.setPreferredSize(new java.awt.Dimension(80, 36));
        viewAllButtonGroup.add(viewAllBackButton);

        viewAllCard.add(viewAllButtonGroup, java.awt.BorderLayout.SOUTH);

        mainFrame.add(viewAllCard, "viewAllCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studyButtonMouseClicked
        CardLayout layout = (CardLayout) mainFrame.getLayout();
        layout.show(mainFrame, "studyCard");
    }//GEN-LAST:event_studyButtonMouseClicked

    private void buildButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildButtonMouseClicked
        CardLayout layout = (CardLayout) mainFrame.getLayout();
        layout.show(mainFrame, "buildCard");
    }//GEN-LAST:event_buildButtonMouseClicked

    private void viewAllButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllButtonMouseClicked
        CardLayout layout = (CardLayout) mainFrame.getLayout();
        layout.show(mainFrame, "viewAllCard");
    }//GEN-LAST:event_viewAllButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCard;
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel allCardsLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backLabel;
    private javax.swing.JPanel backPanel;
    private javax.swing.JTextField backTextField;
    private javax.swing.JButton buildButton;
    private javax.swing.JPanel buildCard;
    private javax.swing.JLabel buildCardLabel;
    private javax.swing.JPanel buttonGroup;
    private javax.swing.JLabel errorLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JPanel flashcardPanel;
    private javax.swing.JButton flipButton;
    private javax.swing.JPanel frontBackPanel;
    private javax.swing.JLabel frontLabel;
    private javax.swing.JTextField frontTextField;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JPanel menuButtons;
    private javax.swing.JPanel menuCard;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel spacerLabel;
    private javax.swing.JButton studyBackButton;
    private javax.swing.JButton studyButton;
    private javax.swing.JPanel studyCard;
    private javax.swing.JLabel studyLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewAllBackButton;
    private javax.swing.JButton viewAllButton;
    private javax.swing.JPanel viewAllButtonGroup;
    private javax.swing.JPanel viewAllCard;
    // End of variables declaration//GEN-END:variables
}
