
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author william.li
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form Cardbulider
     */
    public MainScreen() {
        initComponents();

        setTitle("Flashcard Builder");
        setLocationRelativeTo(null);

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainFrame = new javax.swing.JPanel();
        menuCard = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        spacerLabel = new javax.swing.JLabel();
        menuButtons = new javax.swing.JPanel();
        buildButton = new javax.swing.JButton();
        studyButton = new javax.swing.JButton();
        viewAllButton = new javax.swing.JButton();
        buildCard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studyCard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        viewAllCard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainFrame.setPreferredSize(new java.awt.Dimension(262, 263));
        mainFrame.setLayout(new java.awt.CardLayout());

        menuCard.setLayout(new java.awt.GridLayout(4, 0));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Flashcard Builder");
        menuCard.add(titleLabel);
        menuCard.add(spacerLabel);

        menuButtons.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        buildButton.setText("Build");
        buildButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buildButtonMouseClicked(evt);
            }
        });
        menuButtons.add(buildButton);

        studyButton.setText("Study");
        studyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studyButtonMouseClicked(evt);
            }
        });
        menuButtons.add(studyButton);

        viewAllButton.setText("View All");
        viewAllButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllButtonMouseClicked(evt);
            }
        });
        menuButtons.add(viewAllButton);

        menuCard.add(menuButtons);

        mainFrame.add(menuCard, "menuCard");

        jLabel1.setText("Build card");

        javax.swing.GroupLayout buildCardLayout = new javax.swing.GroupLayout(buildCard);
        buildCard.setLayout(buildCardLayout);
        buildCardLayout.setHorizontalGroup(
            buildCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildCardLayout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        buildCardLayout.setVerticalGroup(
            buildCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildCardLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        mainFrame.add(buildCard, "buildCard");

        jLabel2.setText("Study");

        javax.swing.GroupLayout studyCardLayout = new javax.swing.GroupLayout(studyCard);
        studyCard.setLayout(studyCardLayout);
        studyCardLayout.setHorizontalGroup(
            studyCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studyCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
        );
        studyCardLayout.setVerticalGroup(
            studyCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studyCardLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        mainFrame.add(studyCard, "studyCard");

        jLabel3.setText("View all");

        javax.swing.GroupLayout viewAllCardLayout = new javax.swing.GroupLayout(viewAllCard);
        viewAllCard.setLayout(viewAllCardLayout);
        viewAllCardLayout.setHorizontalGroup(
            viewAllCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewAllCardLayout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
        );
        viewAllCardLayout.setVerticalGroup(
            viewAllCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewAllCardLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        mainFrame.add(viewAllCard, "viewAllCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studyButtonMouseClicked
        CardLayout layout = (CardLayout) mainFrame.getLayout();
        layout.show(mainFrame, "studyCard");
    }//GEN-LAST:event_studyButtonMouseClicked

    private void buildButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildButtonMouseClicked
        CardLayout layout = (CardLayout) mainFrame.getLayout();
        layout.show(mainFrame, "buildCard");
    }//GEN-LAST:event_buildButtonMouseClicked

    private void viewAllButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllButtonMouseClicked
        CardLayout layout = (CardLayout) mainFrame.getLayout();
        layout.show(mainFrame, "viewAllCard");
    }//GEN-LAST:event_viewAllButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buildButton;
    private javax.swing.JPanel buildCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainFrame;
    private javax.swing.JPanel menuButtons;
    private javax.swing.JPanel menuCard;
    private javax.swing.JLabel spacerLabel;
    private javax.swing.JButton studyButton;
    private javax.swing.JPanel studyCard;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewAllButton;
    private javax.swing.JPanel viewAllCard;
    // End of variables declaration//GEN-END:variables
}
